config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'


  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create, :destroy ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]

  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

end

app/views/shared/_calendar.html.erb
<div class="calendar col-6" id="calendar-data" data-start-date="<%= product.start_date.strftime("%e/%m/%Y") %>" data-end-date="<%= product.end_date.strftime("%e/%m/%Y") %>" >
  <span>Sélectionnez des dates</span>
  <div id="reportrange" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc; width: 100%">
      <i class="fa fa-calendar"></i>&nbsp;
      <span></span> <i class="fa fa-caret-down"></i>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
            <%= link_to root_path do %>
            <%= image_tag 'Logo_Bric_N.png', class:"logo"%>
           <% end %>
  <%# <div class="">
      <div class="container d-flex justify-content-center">
        <nav style="--gp-section-max-width:1120px">
          <div class="container-fluid">
            <form class="d-flex" role="search">
              <input class="form-control rounded-pill col-6 me-3" type="search" placeholder="Trouver une oeuvre" aria-label="Une envie ?">
              <button class="btn btn-outline-primary rounded-pill col-4" type="submit">Le(t's) go</button>
            </form>
          </div>
         </nav>
      </div>
  </div> %>
  <%= form_with url: products_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control rounded-pill col-6 me-3",
      placeholder: "Entrez une ville"
    %>
    <%= submit_tag "Le(t's) go", class: "btn btn-outline-primary rounded-pill col-4" %>
  <% end %>

</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
       <% if user_signed_in? %>
          <li class="nav-item dropdown sign-up">
            <img class="avatar dropdown-toggle sign-in" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="/assets/sign_in.png" />
            <img class="overlay" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="/assets/sign_up.png" />

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Profil - <%= current_user.email %></a>
              <a class="dropdown-item" href="<%= my_products_path %>">Mes produits</a>
              <a class="dropdown-item" href="<%= new_product_path %>">Ajouter un produit</a>
              <a class="dropdown-item" href="<%= bookings_path %>">Mes réservations</a>
              <a class="dropdown-item" data-turbo-method="delete" href="<%= destroy_user_session_path %>">Se déconnecter</a>
            </div>
            <% else %>
            <li><%= link_to "S'enregistrer", new_user_registration_path, class: 'btn btn-outline-primary rounded-pill mx-2' %></li>
            <%= link_to "Se connecter", new_user_session_path, class: 'btn btn-outline-primary rounded-pill mx-2' %>

            <% end %>
          </li>

      </ul>
    </div>
  </div>
</div>