config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'


  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create, :destroy ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]

  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user

  has_many :bookings, dependent: :destroy

  has_one_attached :photo
  has_many :reviews, through: :bookings

  validates :title, presence: true, uniqueness: true
  validates :description, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :capacity, presence: true
  validates :price, presence: true


  def status?
    status
  end

  include PgSearch::Model
  pg_search_scope :search_by_city_and_address,
    against: [ :city, :address ],
    using: {
      tsearch: { prefix: true }
    }

  def average_rating
    if self.bookings.empty?
      return {
        average: 0,
        num: 0
      }
    else
      ratings = []
      number = 0
      self.bookings.each do |booking|
        if booking.review
          number += 1
          ratings << booking.review.rating
        else
          next
        end
      end
      if ratings.empty?
        return {
          average: 0,
          num: 0
        }
      else
        return {
          average: ((ratings.sum) / ratings.count),
          num: number
        }
      end
    end
  end

  def reviews
    reviews = []
    unless self.bookings.empty?
      self.bookings.each do |booking|
        reviews << booking.review if booking.review
      end
    end
    return reviews
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  before_action :set_user, :database_search
  before_action :set_product, only: %i[show edit update destroy reviews]

  def index
    #@products = Product.all
    @products = policy_scope(Product)
    if params[:query].present?
      @products = Product.search_by_city_and_address(params[:query])
    else
      @products = Product.all
    end
    @markers = @products.geocoded.map do |product|
      {
        lng: product.longitude,
        lat: product.latitude,
        info_window_html: render_to_string(partial: "info_window", locals: {product: product}),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = @user.id
    @product = current_user.products.build(product_params)
    authorize @product
    if @product.save
     flash[:notice] = "Product successfully listed for sale!"
     redirect_to @product
    else
     flash[:alert] = "Failed to list product for sale. Please try again."
     render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @booking = Booking.new
    @bookings = @product.bookings.where(status: "pending")
  end

  def edit
    Product.find(params[:id])
    authorize @product
  end

  def update
    @product.update(product_params)
    @booking = @product.bookings.find(params[:booking_id])
    if params[:status] == false
      @booking.update(status: "accepted")
      flash[:notice] = "Booking request accepted!"
    elsif params[:status] == false
      @booking.update(status: "rejected")
      flash[:notice] = "Booking request rejected!"
    else
      flash[:alert] = "Invalid status. Please try again."
    end
    redirect_to @product
  end

  def destroy
    @product.destroy
    redirect_to my_products_path
    authorize @products
  end

  def my_products
    @products = current_user.products
    @bookings = @products.map {|p| p.bookings}.flatten
    authorize @products
  end

  def search
    if params[:query].present?
      @products = Product.search_by_city_address(params[:query])
    else
      @products = Product.all
    end
    @count = @products.count
    @query = params[:query]

    @markers = @products.geocoded.map do |product|
      {
        lat: product.latitude,
        lng: product.longitude,
        info_window: render_to_string(partial: "info_window", locals: { product: product }),
        marker_html: render_to_string(partial: "marker", locals: {product: product})
      }
    end
    authorize @products
    authorize @markers
  end

  def reviews
    unless @product.reviews.empty?
      @reviews = @product.reviews
    end
  end

  def status
    @products = Product.where(status: params[:status])
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  def my_bookings_as_owner
    @bookings = Booking.where(product: current_user.products)
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :address, :city, :photo, :capacity, :price, :latitude, :longitude)
  end

  def set_product
    if Product.find_by(id: params[:id]).nil?
      redirect_to error_path
    else
      @product = Product.find(params[:id])
      authorize @product
    end
  end

  def set_user
    @user = current_user
  end

  def database_search
    @markers = Product.all
  end
end

app/views/products/_info_window.html.erb
<%= link_to product do %>
    <% if product.photo.key.nil? %>
    <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
  <% else %>
    <%= cl_image_tag product.photo.key, crop: :fill, class:"img-fluid width: 100% height: auto" %>
  <% end %>

  <div class="map-card">
    <p><span class="" style="font: size 15px;"><i class="fa fa-location-arrow"></i></span>  <%= product.address %> <strong></strong></p>
    <p><span class="" style="font-size:15px;"><i class="fa fa-user"></i></span>  <%= product.title %> </p>
    <p>€/semaine <span class="" style="font-size:30px; text-align:right; font-family:"><%= product.price %></span></p>
  </div>
    <p class='text-center'><%= link_to "Louer", new_product_booking_path(product), class: "btn btn-outline-primary rounded-pill" %>
</p>
<% end %>

app/views/products/_marker.html.erb
<%= image_tag "Symbol_Bric_N.png", height: 50, width: 50, alt: "Logo" %>

app/views/products/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Modifier produits</h2>
  </div>
</div>

<div class="container">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.input :address %>
      <%= f.input :city %>
      <%= f.input :price %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :capacity %>
      <%= f.input :status %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Modifier produits", class: "btn btn-outline-primary" %>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
  </div>
</div>

<div class="px-5 products-map-grid">
      <div id='map' style='width: 100%;'
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

  <div class="product-cards">
    <% @products.each do |product| %>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="products-photo">
            <% if product.photo.attached? %>
              <%= cl_image_tag product.photo.key, class: 'card-img-top index-image' %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"card-img-top my_product_image index-image") %>
            <% end %>
            <h5 class="card-title text-center"><%= link_to product.title, product_path(product) %></h5>
            <p class="card-text"><%= product.description %></p>
            <p class="card-text"><%= product.price %> €/ semaine</p>
            <%= link_to "Voir le produit", product, class: "rounded-pill btn btn-outline-warning" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/my_products.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
  </div>
</div>

<div class="my_products_page">
  <div class="my_products_container">

    <table>
  <thead>
    <tr>
      <th>Renter</th>
      <th>Dates</th>
      <th>Produit</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user_id %></td>
        <td><%= booking.start_date %> to <%= booking.end_date %></td>
        <td><%= booking.product.title %></td>
        <td>
          <% if booking.status == "pending" %>
          <%= link_to "Accept", accept_booking_path(booking), method: :get, class: "btn btn-success" %>
          <%= link_to "Reject", reject_booking_path(booking), method: :get, class: "btn btn-danger" %>
          <% else %>
            <% if booking.update(status: "accepted") %>
              <%= booking.destroy %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

    <% unless current_user.products.nil? %>
      <% @products.each do |product| %>
        <div class="product_row">
          <div class="photo">
            <% if product.photo.key.present? %>
              <%= cl_image_tag(product.photo.key, class:"my-product-image") %>
            <% else %>
              <%= image_tag("unknown.jpg", class:"my-product-image") %>
            <% end %>
            <p><%= product.address %></p>
          </div>

          <div class="d-flex align-items-center">
            <% if policy(product).edit? %>
              <%= link_to 'Edit', edit_product_path(product), class:"btn btn-primary" %>
            <% end %>
            <% unless product.bookings.any? %>
          <div class="remove_product_button">

            <%= link_to product_path(product), method:"delete", data: { confirm: "Êtes-vous sûr?" }, class:"bin" do %>
            <i class="fa fa-trash" aria-hidden="true"></i>

            <% end %>
          </div>
          </div>
          <% else %>
          <div class="remove_product_button_disabled">
            <i class="fa fa-trash" aria-hidden="true" title="Ce produit a une réservation en cours"></i>
          </div>
          <% end %>
          </div>
        </div>
        </div>
        <hr>
      <% end %>
    <% end %>
    <div class="d-flex align-items-center">
    <%= link_to "Ajouter un nouveau produit", new_product_path(@product), class:"btn btn-primary add_new_product" %>
    <%= link_to 'Back to product', products_path, class: "btn btn-primary" %>

    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5 mt-5">Ajouter un produit</h2>
  </div>
</div>
<div class="container d-flex flex-column card p-4 mb-4 shadow w-50 mx-auto">
  <div class="rental_form">
    <%= simple_form_for [ @product ] do |f| %>
      <%= f.input :title, label: 'Titre' %>
      <%= f.input :description, label: 'Description' %>
      <%= f.input :price, label: 'Prix à la semaine' %>
      <%= f.input :city, label: 'Ville' %>
      <%= f.input :address, label: 'Adresse' %>
      <%= f.input :capacity, label: 'Nombre de pièces' %>
      <%= f.input :photo, as: :file %>
      <div class="col text-center mt-5">
        <%= f.submit "Ajouter mon produit", class: "btn btn-outline-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/products/reviews.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Mes avis</h1>
  </div>
</div>

<h1><span class="text-muted"><%= @product.address %></span> Reviews (<%= @product.reviews.count %> opinions)</h1>
<div class="container">
  <div class="row d-flex justify-content-center">
    <% @product.reviews.each do |review| %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @product.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @product.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Back to product', product_path(@product), class: "btn btn-primary" %>
</div>

app/views/products/search.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Produits disponibles</h2>
  </div>
</div>

<% @search_colon = @query.present? ? ":" : ""  %>
<% @search_text =  @count > 1 || @count == 0 ? "stays" : "stay" %>
<h1 class="text-center">Tous les produits disponibles</h1>
<h3 class="text-center"><%= @query.capitalize %> <%= @search_colon %> <%= @count %> <%=@search_text %> found </h3>
<div class="px-5 products-map-grid">
    <div id='map' style='width: 100%;'
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <div class="product-cards">
    <% @products.each do |product| %>
    <div>
      <div class="card mb-2">
        <div class="card-block p-3">
          <div class="products-photo">
            <% if product.photo.key.present? %>
              <%= cl_image_tag product.photo.key, class:"card-img-top search-image " %>
            <% else %>
            <%= image_tag("unknown.jpg", class:"card-img-top search-image") %>
            <% end %>
          </div>
          <strong><p class="card-title"><%= product.address %></p></strong>
          <p class="card-subtitle text-muted"><span class="font-weight-bold">Price:</span> <%= product.price %> Euros</p>
          <small class="card-text p-y-1"><span class="font-weight-bold">Capacity:</span> <%= product.capacity %> people</small><br>
          <%= link_to 'Check it out!', product, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<h1><%= link_to "Retournez à la page d'accueil", root_path, class: "btn btn-primary" %></h1>

app/views/products/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
  </div>
</div>

<div class="container d-flex flex-column card p-4 mb-4 shadow w-75 mx-auto">
    <div class="product-data d-flex">
        <div class="d-flex justify-content-between  rounded">
          <% if @product.photo.attached? %>
          <%= cl_image_tag @product.photo.key, class: 'img-fluid rounded-start' %>
          <% else %>
            <%= image_tag("unknown.jpg", class:"show-image") %>
          <% end %>
        </div>

      <div class="product_show_info">
        <h1 class="card-text"><%= @product.title %></h1>
      <div class="card-text">
          <p><strong>Description : </strong><%= @product.description %></p>
          <p><strong>Nombre de pièces : </strong><%= @product.capacity %></p>
          <p><strong>Adresse : </strong><%= @product.address %>
          <p><strong>Ville : </strong><%= @product.city %></p>
          <p><strong>Prix ​​par semaine : </strong><%= @product.price %>€</p>
          <% if @product.status? %>
            <p class="card-text text-success"><strong>Disponible</strong></p><br>
          <% else %>
            <p class="card-text"><strong>Indisponible</strong></p><br>
          <% end %>
          <%= link_to "Faire une demande de location", "/products/#{params[:id]}/bookings/new", class: "btn btn-primary" %>
        </p>
      </div>
      </div>

  </div>
</div>
      <hr>

    <%# <div class="d-flex flex-row product-options"> %>
      <%# <% if policy(Product).create? %>
        <%# <%= link_to "Ajouter produits", new_product_path, class: "btn btn-primary h-25" %>
      <%# <% end %>
      <%# <% if policy(@product).edit? %>
        <%# <%= link_to 'Modifier', edit_product_path(@product), class:"btn btn-primary" %>
      <%# <% end %>
      <%# <% if policy(@product).destroy? %>
        <%# <%= link_to 'Supprimer', product_path(@product), method: :delete, class:"btn btn-primary", data: {confirm: "Êtes-vous sûr ??"} %>
      <%# <% end %>
      <%# <% if policy(Product).create? %>
        <%# <%= link_to "Retour à Tous les produits", products_path, class: "btn btn-primary"  %>
      <%# <% end %>
    <%# </div> %>